development:
  access_key_id: <%= Figaro.env.aws_access_key_id %>
  secret_access_key: <%= Figaro.env.aws_secret_access_key %>
  aws_access_key_id: <%= Figaro.env.aws_access_key_id %>
  aws_secret_access_key: <%= Figaro.env.aws_secret_access_key %>
test:
  access_key_id: <%= Figaro.env.aws_access_key_id %>
  secret_access_key: <%= Figaro.env.aws_secret_access_key %>
production:
  access_key_id: <%= Figaro.env.aws_access_key_id %>
  secret_access_key: <%= Figaro.env.aws_secret_access_key %>
  aws_access_key_id: <%= Figaro.env.aws_access_key_id %>
  aws_secret_access_key: <%= Figaro.env.aws_secret_access_key %>