development:
  access_key_id: <%= Figaro.env.access_key_id %>
  secret_access_key: <%= Figaro.env.secret_access_key %>
test:
  access_key_id: <%= Figaro.env.access_key_id %>
  secret_access_key: <%= Figaro.env.secret_access_key %>
production:
  access_key_id: <%= Figaro.env.access_key_id %>
  secret_access_key: <%= Figaro.env.secret_access_key %>