# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9d9053a75e7dac3a2e90c02ae0b7e579ac6b51a64e73974df69050464cfb38da1cf292da53a5d2ecb6036696ad045adb9e6b2541a18f2c18a470da74f7db81e

test:
  secret_key_base: a85d265aff9646696bb1395495652fa5a6f26434122c401b498e9c98c975c14c8e9b430ffe6261883e52244afc51213fe5bde7d0517c1f4529053f63e51ff0d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
